name: Share data between jobs

on: [push]

jobs:
  run-script:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: |
            DIR=`ls .` && echo $DIR
